### ISSUE TITLE
Upgrade needed to use the latest xml format

### ISSUE THREAD

**Issue by torkos** [Vertabelo/vertabelo-flask#1]
I get errors when I try to run this script on an exported xml.  But I do not get errors when I try to run the vertabelo-sqlalchemy script because that script has been updated to read the latest xml format.

Can you update this script as well?

**Comment by pdybka-ep** [comment]
Hi, 
The script was updated. Thanks for pointing this out.
If you have any problems with generation, don't hesitate to contact me.
